export const MimeTypeByExtension: Record<string, string> = Object.freeze({
    ".md": "text/markdown",
    ".html": "text/html",
    ".htm": "text/html",
    ".json": "application/json",
    ".map": "application/json",
    ".txt": "text/plain",
    ".ts": "text/typescript",
    ".tsx": "text/tsx",
    ".js": "application/javascript",
    ".jsx": "text/jsx",
    ".gz": "application/gzip",
    ".css": "text/css",
    ".wasm": "application/wasm",
    ".mjs": "application/javascript",
    ".otf": "font/otf",
    ".ttf": "font/ttf",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".conf": "text/plain",
    ".list": "text/plain",
    ".log": "text/plain",
    ".ini": "text/plain",
    ".vtt": "text/vtt",
    ".yaml": "text/yaml",
    ".yml": "text/yaml",
    ".mid": "audio/midi",
    ".midi": "audio/midi",
    ".mp3": "audio/mp3",
    ".mp4a": "audio/mp4",
    ".m4a": "audio/mp4",
    ".ogg": "audio/ogg",
    ".spx": "audio/ogg",
    ".opus": "audio/ogg",
    ".wav": "audio/wav",
    ".webm": "audio/webm",
    ".aac": "audio/x-aac",
    ".flac": "audio/x-flac",
    ".mp4": "video/mp4",
    ".mp4v": "video/mp4",
    ".mkv": "video/x-matroska",
    ".mov": "video/quicktime",
    ".svg": "image/svg+xml",
    ".avif": "image/avif",
    ".bmp": "image/bmp",
    ".gif": "image/gif",
    ".heic": "image/heic",
    ".heif": "image/heif",
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".png": "image/png",
    ".tiff": "image/tiff",
    ".psd": "image/vnd.adobe.photoshop",
    ".ico": "image/vnd.microsoft.icon",
    ".webp": "image/webp",
    ".es": "application/ecmascript",
    ".epub": "application/epub+zip",
    ".jar": "application/java-archive",
    ".war": "application/java-archive",
    ".webmanifest": "application/manifest+json",
    ".doc": "application/msword",
    ".dot": "application/msword",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".dotx": "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    ".cjs": "application/node",
    ".bin": "application/octet-stream",
    ".pkg": "application/octet-stream",
    ".dump": "application/octet-stream",
    ".exe": "application/octet-stream",
    ".deploy": "application/octet-stream",
    ".img": "application/octet-stream",
    ".msi": "application/octet-stream",
    ".pdf": "application/pdf",
    ".pgp": "application/pgp-encrypted",
    ".asc": "application/pgp-signature",
    ".sig": "application/pgp-signature",
    ".ai": "application/postscript",
    ".eps": "application/postscript",
    ".ps": "application/postscript",
    ".rdf": "application/rdf+xml",
    ".rss": "application/rss+xml",
    ".rtf": "application/rtf",
    ".apk": "application/vnd.android.package-archive",
    ".key": "application/vnd.apple.keynote",
    ".numbers": "application/vnd.apple.keynote",
    ".pages": "application/vnd.apple.pages",
    ".geo": "application/vnd.dynageo",
    ".gdoc": "application/vnd.google-apps.document",
    ".gslides": "application/vnd.google-apps.presentation",
    ".gsheet": "application/vnd.google-apps.spreadsheet",
    ".kml": "application/vnd.google-earth.kml+xml",
    ".mkz": "application/vnd.google-earth.kmz",
    ".icc": "application/vnd.iccprofile",
    ".icm": "application/vnd.iccprofile",
    ".xls": "application/vnd.ms-excel",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".xlm": "application/vnd.ms-excel",
    ".ppt": "application/vnd.ms-powerpoint",
    ".pot": "application/vnd.ms-powerpoint",
    ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".potx": "application/vnd.openxmlformats-officedocument.presentationml.template",
    ".xps": "application/vnd.ms-xpsdocument",
    ".odc": "application/vnd.oasis.opendocument.chart",
    ".odb": "application/vnd.oasis.opendocument.database",
    ".odf": "application/vnd.oasis.opendocument.formula",
    ".odg": "application/vnd.oasis.opendocument.graphics",
    ".odp": "application/vnd.oasis.opendocument.presentation",
    ".ods": "application/vnd.oasis.opendocument.spreadsheet",
    ".odt": "application/vnd.oasis.opendocument.text",
    ".rar": "application/vnd.rar",
    ".unityweb": "application/vnd.unity",
    ".dmg": "application/x-apple-diskimage",
    ".bz": "application/x-bzip",
    ".crx": "application/x-chrome-extension",
    ".deb": "application/x-debian-package",
    ".php": "application/x-httpd-php",
    ".iso": "application/x-iso9660-image",
    ".sh": "application/x-sh",
    ".sql": "application/x-sql",
    ".srt": "application/x-subrip",
    ".xml": "application/xml",
    ".zip": "application/zip",
});

export const ExtensionByMimeType: Record<string, string[]> = Object.freeze({
    "text/markdown": [".md"],
    "text/html": [".html", ".htm"],
    "application/json": [".json", ".map"],
    "text/plain": [".txt", ".conf", ".list", ".log", ".ini"],
    "text/typescript": [".ts"],
    "text/tsx": [".tsx"],
    "application/javascript": [".js", ".mjs"],
    "text/jsx": [".jsx"],
    "application/gzip": [".gz"],
    "text/css": [".css"],
    "application/wasm": [".wasm"],
    "font/otf": [".otf"],
    "font/ttf": [".ttf"],
    "font/woff": [".woff"],
    "font/woff2": [".woff2"],
    "text/vtt": [".vtt"],
    "text/yaml": [".yaml", ".yml"],
    "audio/midi": [".mid", ".midi"],
    "audio/mp3": [".mp3"],
    "audio/mp4": [".mp4a", ".m4a", ".mp4", ".mp4v"],
    "audio/ogg": [".ogg", ".spx", ".opus"],
    "audio/wav": [".wav"],
    "audio/webm": [".webm"],
    "audio/x-aac": [".aac"],
    "audio/x-flac": [".flac"],
    "video/x-matroska": [".mkv"],
    "video/quicktime": [".mov"],
    "image/svg+xml": [".svg"],
    "image/avif": [".avif"],
    "image/bmp": [".bmp"],
    "image/gif": [".gif"],
    "image/heic": [".heic"],
    "image/heif": [".heif"],
    "image/jpeg": [".jpeg", ".jpg"],
    "image/png": [".png"],
    "image/tiff": [".tiff"],
    "image/vnd.adobe.photoshop": [".psd"],
    "image/vnd.microsoft.icon": [".ico"],
    "image/webp": [".webp"],
    "application/ecmascript": [".es"],
    "application/epub+zip": [".epub"],
    "application/java-archive": [".jar", ".war"],
    "application/manifest+json": [".webmanifest"],
    "application/msword": [".doc", ".dot"],
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"],
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template": [".dotx"],
    "application/node": [".cjs"],
    "application/octet-stream": [".bin", ".pkg", ".dump", ".exe", ".deploy", ".img", ".msi"],
    "application/pdf": [".pdf"],
    "application/pgp-encrypted": [".pgp", ".gpg"],
    "application/pgp-signature": [".asc", ".sig"],
    "application/postscript": [".ai", ".eps", ".ps"],
    "application/rdf+xml": [".rdf"],
    "application/rss+xml": [".rss"],
    "application/rtf": [".rtf"],
    "application/vnd.android.package-archive": [".apk"],
    "application/vnd.apple.keynote": [".key", ".keynote"],
    "application/vnd.apple.pages": [".pages"],
    "application/vnd.dynageo": [".geo"],
    "application/vnd.google-apps.document": [".gdoc"],
    "application/vnd.google-apps.presentation": [".gslides"],
    "application/vnd.google-apps.spreadsheet": [".gsheet"],
    "application/vnd.google-earth.kml+xml": [".kml"],
    "application/vnd.google-earth.kmz": [".mkz"],
    "application/vnd.iccprofile": [".icc", ".icm"],
    "application/vnd.ms-excel": [".xls", ".xlt", ".xla", ".xlsx", ".xltx", ".xlsm", ".xltm", ".xlam", ".xlsb"],
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"],
    "application/vnd.ms-powerpoint": [".ppt", ".pot", ".pps", ".ppa", ".pptx", ".potx", ".ppsx", ".ppam", ".pptm", ".potm", ".ppsm"],
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": [".pptx"],
    "application/vnd.openxmlformats-officedocument.presentationml.template": [".potx"],
    "application/vnd.ms-xpsdocument": [".xps"],
    "application/vnd.oasis.opendocument.chart": [".odc"],
    "application/vnd.oasis.opendocument.database": [".odb"],
    "application/vnd.oasis.opendocument.formula": [".odf"],
    "application/vnd.oasis.opendocument.graphics": [".odg"],
    "application/vnd.oasis.opendocument.presentation": [".odp"],
    "application/vnd.oasis.opendocument.spreadsheet": [".ods"],
    "application/vnd.oasis.opendocument.text": [".odt"],
    "application/vnd.rar": [".rar"],
    "application/vnd.unity": [".unityweb"],
    "application/x-apple-diskimage": [".dmg"],
    "application/x-bzip": [".bz"],
    "application/x-chrome-extension": [".crx"],
    "application/x-debian-package": [".deb"],
    "application/x-httpd-php": [".php"],
    "application/x-iso9660-image": [".iso"],
    "application/x-sh": [".sh"],
    "application/x-sql": [".sql"],
    "application/x-subrip": [".srt"],
    "application/xml": [".xml"],
    "application/zip": [".zip"],
});